services:
  app:
    build:
      context: .
    container_name: tsr
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./res:/app/res:ro
    restart: unless-stopped

